<?php

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;
/** lfaleekage */

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/LFA/composer/InstalledVersions.php',
    'LFA\\OCA\\Files\\Activity\\FavoriteProvider' => $baseDir . '/../lib/Activity/FavoriteProvider.php',
    'LFA\\OCA\\Files\\Activity\\Filter\\Favorites' => $baseDir . '/../lib/Activity/Filter/Favorites.php',
    'LFA\\OCA\\Files\\Activity\\Filter\\FileChanges' => $baseDir . '/../lib/Activity/Filter/FileChanges.php',
    'LFA\\OCA\\Files\\Activity\\Helper' => $baseDir . '/../lib/Activity/Helper.php',
    'LFA\\OCA\\Files\\Activity\\Provider' => $baseDir . '/../lib/Activity/Provider.php',
    'LFA\\OCA\\Files\\Activity\\Settings\\FavoriteAction' => $baseDir . '/../lib/Activity/Settings/FavoriteAction.php',
    'LFA\\OCA\\Files\\Activity\\Settings\\FileActivitySettings' => $baseDir . '/../lib/Activity/Settings/FileActivitySettings.php',
    'LFA\\OCA\\Files\\Activity\\Settings\\FileChanged' => $baseDir . '/../lib/Activity/Settings/FileChanged.php',
    'LFA\\OCA\\Files\\Activity\\Settings\\FileFavoriteChanged' => $baseDir . '/../lib/Activity/Settings/FileFavoriteChanged.php',
    'LFA\\OCA\\Files\\App' => $baseDir . '/../lib/App.php',
    'LFA\\OCA\\Files\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'LFA\\OCA\\Files\\BackgroundJob\\CleanupDirectEditingTokens' => $baseDir . '/../lib/BackgroundJob/CleanupDirectEditingTokens.php',
    'LFA\\OCA\\Files\\BackgroundJob\\CleanupFileLocks' => $baseDir . '/../lib/BackgroundJob/CleanupFileLocks.php',
    'LFA\\OCA\\Files\\BackgroundJob\\DeleteOrphanedItems' => $baseDir . '/../lib/BackgroundJob/DeleteOrphanedItems.php',
    'LFA\\OCA\\Files\\BackgroundJob\\ScanFiles' => $baseDir . '/../lib/BackgroundJob/ScanFiles.php',
    'LFA\\OCA\\Files\\BackgroundJob\\TransferOwnership' => $baseDir . '/../lib/BackgroundJob/TransferOwnership.php',
    'LFA\\OCA\\Files\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'LFA\\OCA\\Files\\Collaboration\\Resources\\Listener' => $baseDir . '/../lib/Collaboration/Resources/Listener.php',
    'LFA\\OCA\\Files\\Collaboration\\Resources\\ResourceProvider' => $baseDir . '/../lib/Collaboration/Resources/ResourceProvider.php',
    'LFA\\OCA\\Files\\Command\\DeleteOrphanedFiles' => $baseDir . '/../lib/Command/DeleteOrphanedFiles.php',
    'LFA\\OCA\\Files\\Command\\RepairTree' => $baseDir . '/../lib/Command/RepairTree.php',
    'LFA\\OCA\\Files\\Command\\Scan' => $baseDir . '/../lib/Command/Scan.php',
    'LFA\\OCA\\Files\\Command\\ScanAppData' => $baseDir . '/../lib/Command/ScanAppData.php',
    'LFA\\OCA\\Files\\Command\\TransferOwnership' => $baseDir . '/../lib/Command/TransferOwnership.php',
    'LFA\\OCA\\Files\\Controller\\AjaxController' => $baseDir . '/../lib/Controller/AjaxController.php',
    'LFA\\OCA\\Files\\Controller\\ApiController' => $baseDir . '/../lib/Controller/ApiController.php',
    'LFA\\OCA\\Files\\Controller\\DirectEditingController' => $baseDir . '/../lib/Controller/DirectEditingController.php',
    'LFA\\OCA\\Files\\Controller\\DirectEditingViewController' => $baseDir . '/../lib/Controller/DirectEditingViewController.php',
    'LFA\\OCA\\Files\\Controller\\TemplateController' => $baseDir . '/../lib/Controller/TemplateController.php',
    'LFA\\OCA\\Files\\Controller\\TransferOwnershipController' => $baseDir . '/../lib/Controller/TransferOwnershipController.php',
    'LFA\\OCA\\Files\\Controller\\ViewController' => $baseDir . '/../lib/Controller/ViewController.php',
    'LFA\\OCA\\Files\\Db\\TransferOwnership' => $baseDir . '/../lib/Db/TransferOwnership.php',
    'LFA\\OCA\\Files\\Db\\TransferOwnershipMapper' => $baseDir . '/../lib/Db/TransferOwnershipMapper.php',
    'LFA\\OCA\\Files\\DirectEditingCapabilities' => $baseDir . '/../lib/DirectEditingCapabilities.php',
    'LFA\\OCA\\Files\\Event\\LoadAdditionalScriptsEvent' => $baseDir . '/../lib/Event/LoadAdditionalScriptsEvent.php',
    'LFA\\OCA\\Files\\Event\\LoadSidebar' => $baseDir . '/../lib/Event/LoadSidebar.php',
    'LFA\\OCA\\Files\\Exception\\TransferOwnershipException' => $baseDir . '/../lib/Exception/TransferOwnershipException.php',
    'LFA\\OCA\\Files\\Helper' => $baseDir . '/../lib/Helper.php',
    'LFA\\OCA\\Files\\Listener\\LegacyLoadAdditionalScriptsAdapter' => $baseDir . '/../lib/Listener/LegacyLoadAdditionalScriptsAdapter.php',
    'LFA\\OCA\\Files\\Listener\\LoadSidebarListener' => $baseDir . '/../lib/Listener/LoadSidebarListener.php',
    'LFA\\OCA\\Files\\Migration\\Version11301Date20191205150729' => $baseDir . '/../lib/Migration/Version11301Date20191205150729.php',
    'LFA\\OCA\\Files\\Notification\\Notifier' => $baseDir . '/../lib/Notification/Notifier.php',
    'LFA\\OCA\\Files\\Search\\FilesSearchProvider' => $baseDir . '/../lib/Search/FilesSearchProvider.php',
    'LFA\\OCA\\Files\\Service\\DirectEditingService' => $baseDir . '/../lib/Service/DirectEditingService.php',
    'LFA\\OCA\\Files\\Service\\OwnershipTransferService' => $baseDir . '/../lib/Service/OwnershipTransferService.php',
    'LFA\\OCA\\Files\\Service\\TagService' => $baseDir . '/../lib/Service/TagService.php',
    'LFA\\OCA\\Files\\Settings\\PersonalSettings' => $baseDir . '/../lib/Settings/PersonalSettings.php',
);
/** LFAsnippets */